language: python

python:
  - 3.6

services:
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
    - postgresql-11-postgis-2.5

env:
  global:
  - PGPORT=5433

before_script:
  - psql -c 'create database test;' -U postgres
  - psql -U postgres -d test -c "create extension postgis"
  - psql -U postgres -d test -c "create extension mobilitydb"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install ".[test]" . # install package + test dependencies

script: pytest # run tests

after_success:
  - codecov # submit coverage

